--liquibase formatted sql

--changeset rustdv:20260321-01-create-qrtz-schema
CREATE SCHEMA IF NOT EXISTS qrtz;
--rollback DROP SCHEMA IF EXISTS qrtz CASCADE;

--changeset rustdv:20260321-02-create-qrtz_job_details-table
CREATE TABLE qrtz.QRTZ_JOB_DETAILS
(
    SCHED_NAME        VARCHAR(120) NOT NULL,
    JOB_NAME          VARCHAR(200) NOT NULL,
    JOB_GROUP         VARCHAR(200) NOT NULL,
    DESCRIPTION       VARCHAR(250) NULL,
    JOB_CLASS_NAME    VARCHAR(250) NOT NULL,
    IS_DURABLE        BOOL         NOT NULL,
    IS_NONCONCURRENT  BOOL         NOT NULL,
    IS_UPDATE_DATA    BOOL         NOT NULL,
    REQUESTS_RECOVERY BOOL         NOT NULL,
    JOB_DATA          BYTEA NULL,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_JOB_DETAILS;

--changeset rustdv:20260321-03-create-qrtz_triggers-table
CREATE TABLE qrtz.QRTZ_TRIGGERS
(
    SCHED_NAME     VARCHAR(120) NOT NULL,
    TRIGGER_NAME   VARCHAR(200) NOT NULL,
    TRIGGER_GROUP  VARCHAR(200) NOT NULL,
    JOB_NAME       VARCHAR(200) NOT NULL,
    JOB_GROUP      VARCHAR(200) NOT NULL,
    DESCRIPTION    VARCHAR(250) NULL,
    NEXT_FIRE_TIME BIGINT NULL,
    PREV_FIRE_TIME BIGINT NULL,
    PRIORITY       INTEGER NULL,
    TRIGGER_STATE  VARCHAR(16)  NOT NULL,
    TRIGGER_TYPE   VARCHAR(8)   NOT NULL,
    START_TIME     BIGINT       NOT NULL,
    END_TIME       BIGINT NULL,
    CALENDAR_NAME  VARCHAR(200) NULL,
    MISFIRE_INSTR  SMALLINT NULL,
    JOB_DATA       BYTEA NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES qrtz.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_TRIGGERS;

--changeset rustdv:20260321-04-create-qrtz_simple_triggers-table
CREATE TABLE qrtz.QRTZ_SIMPLE_TRIGGERS
(
    SCHED_NAME      VARCHAR(120) NOT NULL,
    TRIGGER_NAME    VARCHAR(200) NOT NULL,
    TRIGGER_GROUP   VARCHAR(200) NOT NULL,
    REPEAT_COUNT    BIGINT       NOT NULL,
    REPEAT_INTERVAL BIGINT       NOT NULL,
    TIMES_TRIGGERED BIGINT       NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_SIMPLE_TRIGGERS;

--changeset rustdv:20260321-05-create-qrtz_cron_triggers-table
CREATE TABLE qrtz.QRTZ_CRON_TRIGGERS
(
    SCHED_NAME      VARCHAR(120) NOT NULL,
    TRIGGER_NAME    VARCHAR(200) NOT NULL,
    TRIGGER_GROUP   VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(120) NOT NULL,
    TIME_ZONE_ID    VARCHAR(80),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_CRON_TRIGGERS;

--changeset rustdv:20260321-06-create-qrtz_simprop_triggers-table
CREATE TABLE qrtz.QRTZ_SIMPROP_TRIGGERS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_NAME  VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1    VARCHAR(512) NULL,
    STR_PROP_2    VARCHAR(512) NULL,
    STR_PROP_3    VARCHAR(512) NULL,
    INT_PROP_1    INT NULL,
    INT_PROP_2    INT NULL,
    LONG_PROP_1   BIGINT NULL,
    LONG_PROP_2   BIGINT NULL,
    DEC_PROP_1    NUMERIC(13, 4) NULL,
    DEC_PROP_2    NUMERIC(13, 4) NULL,
    BOOL_PROP_1   BOOL NULL,
    BOOL_PROP_2   BOOL NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_SIMPROP_TRIGGERS;

--changeset rustdv:20260321-07-create-qrtz_blob_triggers-table
CREATE TABLE qrtz.QRTZ_BLOB_TRIGGERS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_NAME  VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA     BYTEA NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_BLOB_TRIGGERS;

--changeset rustdv:20260321-08-create-qrtz_calendars-table
CREATE TABLE qrtz.QRTZ_CALENDARS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR      BYTEA        NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_CALENDARS;

--changeset rustdv:20260321-09-create-qrtz_paused_trigger_grps-table
CREATE TABLE qrtz.QRTZ_PAUSED_TRIGGER_GRPS
(
    SCHED_NAME    VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_PAUSED_TRIGGER_GRPS;

--changeset rustdv:20260321-10-create-qrtz_fired_triggers-table
CREATE TABLE qrtz.QRTZ_FIRED_TRIGGERS
(
    SCHED_NAME        VARCHAR(120) NOT NULL,
    ENTRY_ID          VARCHAR(95)  NOT NULL,
    TRIGGER_NAME      VARCHAR(200) NOT NULL,
    TRIGGER_GROUP     VARCHAR(200) NOT NULL,
    INSTANCE_NAME     VARCHAR(200) NOT NULL,
    FIRED_TIME        BIGINT       NOT NULL,
    SCHED_TIME        BIGINT       NOT NULL,
    PRIORITY          INTEGER      NOT NULL,
    STATE             VARCHAR(16)  NOT NULL,
    JOB_NAME          VARCHAR(200) NULL,
    JOB_GROUP         VARCHAR(200) NULL,
    IS_NONCONCURRENT  BOOL NULL,
    REQUESTS_RECOVERY BOOL NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_FIRED_TRIGGERS;

--changeset rustdv:20260321-11-create-qrtz_scheduler_state-table
CREATE TABLE qrtz.QRTZ_SCHEDULER_STATE
(
    SCHED_NAME        VARCHAR(120) NOT NULL,
    INSTANCE_NAME     VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT       NOT NULL,
    CHECKIN_INTERVAL  BIGINT       NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_SCHEDULER_STATE;

--changeset rustdv:20260321-12-create-qrtz_locks-table
CREATE TABLE qrtz.QRTZ_LOCKS
(
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME  VARCHAR(40)  NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
--rollback DROP TABLE IF EXISTS qrtz.QRTZ_LOCKS;

--changeset rustdv:20260321-13-create-qrtz_job_details-indexes
CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY
    ON qrtz.QRTZ_JOB_DETAILS (SCHED_NAME, REQUESTS_RECOVERY);

CREATE INDEX IDX_QRTZ_J_GRP
    ON qrtz.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_GROUP);
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_J_REQ_RECOVERY;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_J_GRP;

--changeset rustdv:20260321-14-create-qrtz_triggers-indexes
CREATE INDEX IDX_QRTZ_T_J
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_JG
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_C
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, CALENDAR_NAME);

CREATE INDEX IDX_QRTZ_T_G
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);

CREATE INDEX IDX_QRTZ_T_STATE
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_N_STATE
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_N_G_STATE
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME);

CREATE INDEX IDX_QRTZ_T_NFT_ST
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);

CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);

CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP
    ON qrtz.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_J;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_JG;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_C;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_G;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_STATE;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_N_STATE;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_N_G_STATE;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_NEXT_FIRE_TIME;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_NFT_ST;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_NFT_MISFIRE;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_NFT_ST_MISFIRE;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_T_NFT_ST_MISFIRE_GRP;

--changeset rustdv:20260321-15-create-qrtz_fired_triggers-indexes
CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME
    ON qrtz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME);

CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY
    ON qrtz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);

CREATE INDEX IDX_QRTZ_FT_J_G
    ON qrtz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_FT_JG
    ON qrtz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_FT_T_G
    ON qrtz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

CREATE INDEX IDX_QRTZ_FT_TG
    ON qrtz.QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_FT_TRIG_INST_NAME;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_FT_INST_JOB_REQ_RCVRY;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_FT_J_G;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_FT_JG;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_FT_T_G;
--rollback DROP INDEX IF EXISTS qrtz.IDX_QRTZ_FT_TG;