server:
  port: ${APP_PORT}

spring:
  config:
    import: optional:file:./mindly-application/.env[.properties]
  application:
    name: mindly
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_NAME}?currentSchema=${PG_SCHEMA}
    password: ${PG_PASSWORD}
    username: ${PG_USERNAME}
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 20000
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master/db.changelog-master.yaml
    default-schema: ${PG_SCHEMA}
    enabled: true
    liquibase-schema: liquibase


